# Docker Compose configuration for local development

services:
  wordsmith-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wordsmith-bot-dev
    restart: unless-stopped
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./nodemon.json:/app/nodemon.json:ro
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:ro
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    stdin_open: true
    tty: true

volumes:
  node_modules:
