FROM node:24.8.0-alpine3.21

RUN npm install -g pnpm

RUN mkdir app
WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY ./src ./src
COPY tsconfig.json ./
COPY nodemon.json ./

EXPOSE 3000

CMD ["pnpm", "dev"]
