FROM node:24.16.0-alpine

RUN npm install -g pnpm@11.3.0

RUN mkdir app
WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY ./src ./src
COPY tsconfig.json ./
COPY nodemon.json ./

EXPOSE 3000

CMD ["pnpm", "dev"]
