FROM node:26.7.0-alpine

RUN npm install -g pnpm@11.22.0

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./

RUN pnpm install --frozen-lockfile

COPY ./src ./src
COPY tsconfig.json ./
COPY nodemon.json ./

EXPOSE 3000

CMD ["pnpm", "dev"]
