name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run build
    - name: Deploy to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PRODUCTION_URL }}
        username: ${{ secrets.PRODUCTION_USER }}
        port: 22
        key: ${{ secrets.DEPLOYMENT_SSH_PRIVATE_KEY }}
        rm: true
        source: "*"
        target: "/home/${{ secrets.PRODUCTION_USER }}/wordsmith_bot"
    - name: Restart the Bot
      uses: fifsky/ssh-action@master
      with:
        command: |
          sudo systemctl restart wordsmith-bot
        host: ${{ secrets.PRODUCTION_URL }}
        user: ${{ secrets.PRODUCTION_USER }}
        key: ${{ secrets.DEPLOYMENT_SSH_PRIVATE_KEY}}
